### PR TITLE
Update libs

### PR DESCRIPTION
**Pull request by deinok**

### CODE REVIEW

**Comment by rogargon** [comment]
Angular libs under control of Angular-CLI should be updated in coordination with Angular-CLI updates. Moreover, due to breaking changes and deprecations, we will avoid changing to Angular 5 for the moment

**Comment by deinok** [comment]
Could you explain this?: "Angular libs under control of Angular-CLI should be updated in coordination with Angular-CLI updates"

In fact, i have test it all this changes, in order to check breaking changes, and no breaking changes have been detected.
List of breaking changes: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

Its better to have a deprecated API in an updated project than have an outdated project where the same APIs have not been deprecated already.

**Comment by rogargon** [comment]
With AngularCLI, the recommended practice to update a project is to regenerate the project template to get not just the updated package.json, there are also many updates to related configuration files. 

For instance, for Angular 5, the HttpModule has been deprecated and they have introduced the Angular Service Worker that can be configured through new options in AngularCLI.

I've tried to do so but the amount of tslint and related issues that appear will require too much maintenance work from the whole team when the focus should be placed on application functionality, especially now that we are finishing Sprint 2. 

Consequently, we will keep Angular 4 for the moment. This is not a big issue as Angular 5 was just released, and in many cases, it is riskier to adopt a just released version, and the Angular team will also update Angular 4 if any critical issue appears.

**Comment by deinok** [comment]
I think that we are not using the HttpModule (not sure).

Also, this new service workers are not part of Angular4 so there is no problem with this.

Also, the .angular-cli.json dont need any change. In fact the schema.json of the file treats unexisting fields with the default value that its "normaly" the backward compat value.

The TSLint are passing the test (for now, the TSLint is not really strict)

**Pull request closed without merging**
